# Config file for [Air](https://github.com/air-verse/air) in TOML format

# Working directory
root = "."
tmp_dir = "tmp"

[build]
# Command to build your Go application
cmd = "go build -o ./tmp/main ."
# Binary file produced by the build command
bin = "tmp/main"
# Command to run the built binary
full_bin = "./tmp/main"
# Watch these filename extensions
include_ext = ["go", "tpl", "tmpl", "html"]
# Ignore these directories
exclude_dir = ["tmp", "vendor", "docker_essentials"]

[log]
# Show log time
time = true

[color]
# Customize each part's color
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true

[proxy]
# Enable live-reloading on the browser.
enabled = true
proxy_port = 8090
app_port = 3000

